// generated by stringer -type=opCode; DO NOT EDIT

package lql

import "fmt"

const _opCode_name = "LoadPrintJoinRenameProjectRestrictPushvPushaOpEqOpGTOpAndOpOrOpAddOpMult"

var _opCode_index = [...]uint8{4, 9, 13, 19, 26, 34, 39, 44, 48, 52, 57, 61, 66, 72}

func (i opCode) String() string {
	i -= 1
	if i >= opCode(len(_opCode_index)) {
		return fmt.Sprintf("opCode(%d)", i+1)
	}
	hi := _opCode_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _opCode_index[i-1]
	}
	return _opCode_name[lo:hi]
}
